/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Raheela Khanum
 */
public class addMA extends javax.swing.JFrame {

    /**
     * Creates new form addMA
     */
    
    public addMA() {
        initComponents();
        Connect();
        jPanel1.setBackground(new Color(248,38,19,120));
       }

    Connection con;
    PreparedStatement ps; 
    ResultSet rs;
    String Category;
    int CID;
    String Name;
    String ID;
    boolean Signin;
    
    public addMA(String name,boolean Signin,int CID,String Category) {
        initComponents();
        Connect();
        jPanel1.setBackground(new Color(248,38,19,120));
        this.Name=jLabel7.getText();;
        this.Signin=Signin;
        this.CID=CID;
        this.Category=Category;
        ID=jLabel5.getText();
        
        }  
        
       
    
    
    
    public void Connect()
      {
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","Ruk@413255");
              }
          catch(ClassNotFoundException ex)
              {Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
               }
          catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
             }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        pname = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        UploadButton = new javax.swing.JButton();
        Cancel2 = new javax.swing.JButton();
        path = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        pic = new javax.swing.JLabel();
        AddProductButton = new javax.swing.JButton();
        DeleteProductButton = new javax.swing.JButton();
        UpdateProductButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1550, 800));
        setPreferredSize(new java.awt.Dimension(1550, 800));
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 785));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Product Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 90, 210, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Description");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 220, 180, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 360, 100, 40);

        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        desc.setRows(5);
        desc.setTabSize(5);
        jScrollPane1.setViewportView(desc);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 190, 370, 120);

        pname.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel1.add(pname);
        pname.setBounds(220, 90, 410, 50);

        cost.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });
        jPanel1.add(cost);
        cost.setBounds(220, 360, 290, 50);

        UploadButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UploadButton.setText("Upload");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UploadButton);
        UploadButton.setBounds(760, 30, 120, 50);

        Cancel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel2.setText("Cancel");
        Cancel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel2ActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel2);
        Cancel2.setBounds(820, 510, 220, 50);

        path.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        path.setForeground(new java.awt.Color(51, 51, 51));
        path.setText("                                  path name");
        jPanel1.add(path);
        path.setBounds(620, 440, 390, 30);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        pic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pic.setText("                           image");
        pic.setPreferredSize(new java.awt.Dimension(1500, 800));

        jDesktopPane1.setLayer(pic, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pic, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(640, 100, 350, 320);

        AddProductButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddProductButton.setText("Add Product");
        AddProductButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddProductButton);
        AddProductButton.setBounds(20, 510, 220, 50);

        DeleteProductButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteProductButton.setText("Delete Product");
        DeleteProductButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DeleteProductButton.setMaximumSize(new java.awt.Dimension(145, 31));
        DeleteProductButton.setMinimumSize(new java.awt.Dimension(145, 31));
        DeleteProductButton.setPreferredSize(new java.awt.Dimension(145, 31));
        DeleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteProductButton);
        DeleteProductButton.setBounds(280, 510, 220, 50);

        UpdateProductButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpdateProductButton.setText("Update Product");
        UpdateProductButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UpdateProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateProductButton);
        UpdateProductButton.setBounds(570, 510, 220, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(210, 110, 1077, 610);

        jLabel4.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\images (5).jpeg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1550, 800);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 90, 60, 30);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 200, 90, 30);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 50, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costActionPerformed

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        //FileNameExtensionFilter fef=new FileNameExtensionFilter("Images","jpg","png","jpeg");
        //chooser.addChoosableFileFilter(fef);
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        path.setText(filename);
        
        ImageIcon imageicon=new ImageIcon(f.toString());
              //Resize image to fit jLabel
        Image imageFit = imageicon.getImage().getScaledInstance(pic.getWidth(),pic.getHeight(),Image.SCALE_SMOOTH);
        pic.setIcon(new ImageIcon(imageFit));
        
        
        /*try
        {
            File image=new File(filename);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int readNum; (readNum=fis.read(buf))!=-1 ;){
            bos.write(buf, 0, readNum);
            
           }
          photo=bos.toByteArray();
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e); 
             }*/
        
    }//GEN-LAST:event_UploadButtonActionPerformed

    private void Cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //userpage u=new userpage(ID,Name,Signin);
        //u.setVisible(true);
        /*ID=jLabel5.getText();
        userpage u=new userpage(Name,Signin);
        this.setVisible(false);
        u.setVisible(true);
     if(Category=="Mobiles and Accessories")
     {
        MobilesAndAccessories ma=new MobilesAndAccessories(ID,Name,Signin);
        ma.setVisible(true);
        this.setVisible(false);
     }
        else if(Category=="Household and Kitchen Appliances")
     {
        HouseholdAndKitchen hk=new HouseholdAndKitchen(ID,Name,Signin);
        hk.setVisible(true);
        this.setVisible(false);
    } 
         else if(Category=="Furniture")
     {
        Furniture f=new Furniture(ID,Name,Signin);
        f.setVisible(true);
        this.setVisible(false);
    }   
         else if(Category=="Books and Stationery")
     {
        BooksAndStationery b=new BooksAndStationery(ID,Name,Signin);
        b.setVisible(true);
        this.setVisible(false);
    } 
     else if(Category=="Grocery")
     {
        Groceries g=new Groceries(ID,Name,Signin);
        g.setVisible(true);
        this.setVisible(false);
    }                                      
    else if(Category=="Daily Essentials")
     {
        DailyEssentials de=new DailyEssentials(ID,Name,Signin);
        de.setVisible(true);
        this.setVisible(false);
    } */
     
    }//GEN-LAST:event_Cancel2ActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        // TODO add your handling code here:
        try
        {
           
            String ProductName=pname.getText();
            String Description=desc.getText();
            int Price=Integer.parseInt(cost.getText());
            String Pathname=path.getText();
            File image=new File(path.getText());
            InputStream in= new FileInputStream(path.getText());
            FileOutputStream fos=new FileOutputStream(image);
            
            ps=con.prepareStatement("insert into products(p_name,description,c_id,price,category,pathname) values(?,?,?,?,?,?)");
            ps.setString(1,ProductName);
            ps.setString(2,Description);
            ps.setInt(3,CID);
            ps.setInt(4,Price);
            ps.setString(5,Category);
            ps.setString(6,Pathname);
           
            

            ps.executeUpdate();
            
             JOptionPane.showMessageDialog(this,"Product Added!!");
                     
            pname.setText("");
            desc.setText("");
            cost.setText("");
            path.setText("path");
            pic.setText("image");
            pic.setIcon(null);
            
        }

        catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MobilesAndAccessories.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void DeleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductButtonActionPerformed
        // TODO add your handling code here:
        String Pid=jLabel6.getText();
        int opt=JOptionPane.showConfirmDialog(null,"Are you sure to delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(opt==0)
        {
         try
         {
            ps=con.prepareStatement("delete from products where p_id=?");
            ps.setString(1,Pid);
            ps.executeUpdate();
             JOptionPane.showMessageDialog(this,"Product Deleted!!");
             
            pname.setText("");
            desc.setText("");
            path.setText("path");
            cost.setText("");
            pic.setText("image");
            pic.setIcon(null);
            this.setVisible(false);
            
           
            //AddProductButton.setEnabled(false);
        } 
        catch(SQLException ex)
        {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
       
       
    }//GEN-LAST:event_DeleteProductButtonActionPerformed

    private void UpdateProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProductButtonActionPerformed
        // TODO add your handling code here:
        
        try
        {
            String ProductName=pname.getText();
            String Description=desc.getText();
            int Price=Integer.parseInt(cost.getText());
            String Pathname=path.getText();
            String Pid=jLabel6.getText();
            
            ps=con.prepareStatement("update products set p_name=?,description=?,price=?,pathname=? where p_id=?");
            
            ps.setString(1,ProductName);
            ps.setString(2,Description);
            ps.setInt(3,Price);
            ps.setString(4,Pathname);
            ps.setString(5,Pid);
      
            ps.executeUpdate();
            
             JOptionPane.showMessageDialog(this,"Product Updated!!");
       
            pname.setText("");
            desc.setText("");
            path.setText("path");
            cost.setText("");
            pic.setText("image");
            pic.setIcon(null);
            jLabel6.setText("");
            this.setVisible(false);
            
            AddProductButton.setEnabled(false);
        }

        catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateProductButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addMA().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddProductButton;
    private javax.swing.JButton Cancel2;
    public javax.swing.JButton DeleteProductButton;
    public javax.swing.JButton UpdateProductButton;
    private javax.swing.JButton UploadButton;
    public javax.swing.JTextField cost;
    public javax.swing.JTextArea desc;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel path;
    public javax.swing.JLabel pic;
    public javax.swing.JTextField pname;
    // End of variables declaration//GEN-END:variables

byte[] photo=null;
String filename=null;
}
