/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Raheela Khanum
 */
public class EnterCategory extends javax.swing.JFrame {

    /**
     * Creates new form EnterCategory
     */
    public EnterCategory() {
        initComponents();
        jPanel1.setBackground(new Color(65,131,215,100));
        Connect();
    }
    
    Connection con;
    PreparedStatement ps; 
    ResultSet rs;
    
    int CID;
    String Name;
    boolean Signin;

    public EnterCategory(String name,boolean Signin)
    {
      initComponents();
      Connect();
      
      jPanel1.setBackground(new Color(65,131,215,100));
      this.Name=name;
      this.Signin=Signin;
    }
    
    public void Connect()
      {
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","Ruk@413255");
              }
          catch(ClassNotFoundException ex)
              {Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
               }
          catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
             }
      }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Enter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Candara Light", 1, 36)); // NOI18N
        jLabel1.setText("Enter The Category");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 20, 320, 70);

        jTextField1.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(10, 90, 380, 70);

        Enter.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Enter.setText("Enter");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });
        jPanel1.add(Enter);
        Enter.setBounds(130, 200, 130, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 190, 400, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\EC.jpeg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 760, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        // TODO add your handling code here:
        String Category=jTextField1.getText();
        
        try 
        {
            ps=con.prepareStatement("select c_id from categories where c_name=?");
            ps.setString(1,Category);
            rs=ps.executeQuery();
            if(rs.next())
            {
               CID=rs.getInt("c_id");
                addMA ob=new addMA(Name,Signin,CID,Category);
                ob.DeleteProductButton.setEnabled(false);
                ob.UpdateProductButton.setEnabled(false);
                ob.setVisible(true);
                this.setVisible(false);
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(EnterCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
            
            
   
       /*if(Category=="")
       {
           JOptionPane.showMessageDialog(this,"Enter the category name!!");
       }
       else if(Category=="Mobiles and Accessories")
       {
           CID=1;
            addMA ob=new addMA(Name,Signin,CID,Category);
        ob.DeleteProductButton.setEnabled(false);
        ob.DeleteProductButton.setEnabled(false);
        ob.setVisible(true);
        this.setVisible(false);
       }
       else if(Category=="Household and Kitchen Appliances")
       {
           CID=2;
            addMA ob=new addMA(Name,Signin,CID,Category);
        ob.DeleteProductButton.setEnabled(false);
        ob.DeleteProductButton.setEnabled(false);
        ob.setVisible(true);
        this.setVisible(false);
       }
       else if(Category=="Furniture")
       {
           CID=3;
            addMA ob=new addMA(Name,Signin,CID,Category);
        ob.DeleteProductButton.setEnabled(false);
        ob.DeleteProductButton.setEnabled(false);
        ob.setVisible(true);
        this.setVisible(false);
       }
       else if(Category=="Books and Stationery")
       {
           CID=4;
            addMA ob=new addMA(Name,Signin,CID,Category);
        ob.DeleteProductButton.setEnabled(false);
        ob.DeleteProductButton.setEnabled(false);
        ob.setVisible(true);
        this.setVisible(false);
       } 
       else if(Category=="Grocery")
       {
           CID=5;
            addMA ob=new addMA(Name,Signin,CID,Category);
        ob.DeleteProductButton.setEnabled(false);
        ob.DeleteProductButton.setEnabled(false);
        ob.setVisible(true);
        this.setVisible(false);
       } 
       else if(Category=="Daily Essentials")
       {
           CID=6;
            addMA ob=new addMA(Name,Signin,CID,Category);
        ob.DeleteProductButton.setEnabled(false);
        ob.DeleteProductButton.setEnabled(false);
        ob.setVisible(true);
        this.setVisible(false);
       }
       else
       {
           JOptionPane.showMessageDialog(this,"Category doesn't exist!!");
           this.setVisible(false);
        }*/
       
       
    }//GEN-LAST:event_EnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterCategory("Ruksar",true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
