/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Raheela Khanum
 */
public class MyCartSelectedRow extends javax.swing.JFrame {

    /**
     * Creates new form MyCartSelectedRow
     */
    
    Connection con;
    PreparedStatement ps; 
    ResultSet rs;
    boolean Signin;
    String Name;
    String ID;
    
    
    public MyCartSelectedRow(String id,String name,boolean Signin) {
        initComponents();
        Connect();
        //jPanel1.setBackground(new Color(248,38,19,150));
      this.Name=name;
      this.Signin=Signin;
       this.ID=id; 
       jLabel7.setVisible(false);
       totcost.setVisible(false);
       jPanel1.setBackground(new Color(75,119,190,100));
      
    }

    public void Connect()
      {
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","Ruk@413255");
              }
          catch(ClassNotFoundException ex)
              {Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
               }
          catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
             }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cost = new javax.swing.JTextField();
        totcost = new javax.swing.JTextField();
        quan = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1234, 588));
        setPreferredSize(new java.awt.Dimension(1234, 600));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Product Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 80, 180, 42);

        pname.setEditable(false);
        pname.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        pname.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(pname);
        pname.setBounds(200, 70, 270, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Quantity");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 150, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 210, 80, 50);

        update.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(560, 60, 160, 50);

        remove.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel1.add(remove);
        remove.setBounds(560, 140, 170, 50);

        cancel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(560, 230, 160, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Total");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 280, 80, 40);

        cost.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        cost.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(cost);
        cost.setBounds(200, 210, 260, 50);

        totcost.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        totcost.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(totcost);
        totcost.setBounds(200, 280, 260, 50);

        quan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quanStateChanged(evt);
            }
        });
        jPanel1.add(quan);
        quan.setBounds(200, 150, 60, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(140, 110, 760, 350);

        jLabel4.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\VQWxKr.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1230, 590);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 50, 33, 13);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 110, 60, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        ID=jLabel6.getText();
         MyCart cart=new MyCart(ID,Name,Signin);
         this.setVisible(false);
         cart.setVisible(true);
         
    }//GEN-LAST:event_cancelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        int UID=Integer.parseInt(jLabel6.getText());
        int PID=Integer.parseInt(jLabel5.getText());
        ID=jLabel6.getText();
        try
        {
            
            int Quantity=Integer.parseInt(quan.getValue().toString());
            int Price=Integer.parseInt(cost.getText());
            int TotalPrice=Quantity * Price;
            
            ps=con.prepareStatement("update cart set price=?,quantity=?,totalPrice=? where p_id=? and u_id=?");
            
            ps.setInt(1,Price);
            ps.setInt(2,Quantity);
            ps.setInt(3,TotalPrice);
            ps.setInt(4,PID);
            ps.setInt(5,UID);
      
            ps.executeUpdate();
            
             JOptionPane.showMessageDialog(this,"Cart Updated!!");
             
             this.setVisible(false);
             MyCart cart=new MyCart(ID,Name,Signin);
             cart.setVisible(true);
        }
        catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        int UID=Integer.parseInt(jLabel6.getText());
        int PID=Integer.parseInt(jLabel5.getText());
        ID=jLabel6.getText();
        
        //int UID=Integer.parseInt(jLabel6.getText());
        //String pid=jLabel5.getText();
        //int PID=Integer.parseInt(pid);
        int opt=JOptionPane.showConfirmDialog(null,"Are you sure to Remove?","Remove Product",JOptionPane.YES_NO_OPTION);
        if(opt==0)
        {
         try
       {
            ps=con.prepareStatement("delete from cart where p_id=? and u_id=?");
            ps.setInt(1,PID);
            ps.setInt(2,UID);
            
            ps.executeUpdate();
             JOptionPane.showMessageDialog(this,"Product Removed from cart!!");
             
             MyCart cart=new MyCart(ID,Name,Signin);
             this.setVisible(false);
             cart.setVisible(true);
            
       }
       catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_removeActionPerformed

    private void quanStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quanStateChanged
        // TODO add your handling code here:
        //int Quantity=Integer.parseInt(quan.getValue().toString());
        //int Price=Integer.parseInt(cost.getText());
        //int tot= Price * Quantity;
        //totcost.setText(String.valueOf(tot));
    }//GEN-LAST:event_quanStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCartSelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCartSelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCartSelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCartSelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCartSelectedRow("","",false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    public javax.swing.JTextField cost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField pname;
    public javax.swing.JSpinner quan;
    private javax.swing.JButton remove;
    public javax.swing.JTextField totcost;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
