/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;

/**
 *
 * @author Raheela Khanum
 */
public class SelectedRow extends javax.swing.JFrame {

    /**
     * Creates new form SelectedRow
     */
    public SelectedRow() {
        initComponents();
        Connect();
        jPanel1.setBackground(new Color(248,38,19,120));
        //jPanel1.setBackground(new Color(240,52,52,150));
    }

     Connection con;
    PreparedStatement ps; 
    ResultSet rs;
    String Category;
    int CID;
    String Name;
    String Role;
    boolean Signin;
    String ID;
    
    String productName;
    
    public SelectedRow(String name,boolean Signin,int CID,String Category) 
    {
        initComponents();
        Connect();
        jPanel1.setBackground(new Color(248,38,19,150));
        this.Name=name;
        this.Signin=Signin;
        this.CID=CID;
        this.Category=Category;
        productName=pname.getText();
        ID=jLabel6.getText();
        
        
    }
    
    public void Connect()
      {
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","Ruk@413255");
              }
          catch(ClassNotFoundException ex)
              {Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
               }
          catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
             }
      }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        cost = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        pic = new javax.swing.JLabel();
        AddToCart = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        uid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1550, 800));
        setPreferredSize(new java.awt.Dimension(1550, 800));
        setSize(new java.awt.Dimension(1550, 800));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 60, 210, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setText("Description");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 180, 180, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setText("Price");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 290, 90, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel5.setText("Quantity");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 390, 130, 40);

        pname.setEditable(false);
        pname.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jPanel1.add(pname);
        pname.setBounds(290, 60, 350, 50);

        desc.setEditable(false);
        desc.setColumns(20);
        desc.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 140, 320, 110);

        cost.setEditable(false);
        cost.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jPanel1.add(cost);
        cost.setBounds(290, 290, 170, 40);

        jSpinner1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, null, 30, 1));
        jSpinner1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(320, 390, 50, 40);

        jDesktopPane1.add(pic);
        pic.setBounds(0, 0, 450, 380);

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(680, 30, 450, 380);

        AddToCart.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AddToCart.setText("Add To Cart");
        AddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartActionPerformed(evt);
            }
        });
        jPanel1.add(AddToCart);
        AddToCart.setBounds(370, 500, 210, 50);

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel);
        Cancel.setBounds(670, 500, 210, 50);
        jPanel1.add(uid);
        uid.setBounds(0, 10, 60, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(190, 140, 1220, 580);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\images (5).jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1550, 800);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 50, 70, 50);

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(580, 90, 33, 13);

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 610, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartActionPerformed
        // TODO add your handling code here:
    //if(Signin==true)
    //{
      
      String productName=pname.getText();
      int Quantity=Integer.parseInt(jSpinner1.getValue().toString());
      int Price=Integer.parseInt(cost.getText());
      int uid=Integer.parseInt(jLabel6.getText());
      int pid=Integer.parseInt(jLabel7.getText());
      int totprice=Integer.parseInt(jLabel8.getText());
        try{
             ps=con.prepareStatement("insert into cart(u_id,p_id,p_name,quantity,price,totalPrice)values(?,?,?,?,?,?)");
            
             ps.setInt(1,uid);
             ps.setInt(2,pid);
             ps.setString(3,productName);
             ps.setInt(4,Quantity);
             ps.setInt(5,Price);
             ps.setInt(6,totprice);
            
             ps.executeUpdate();
             
             //JOptionPane.showMessageDialog(this,"Product added to cart!");
             //this.setVisible(false);
             
             ps=con.prepareStatement("insert into cart1(u_id,p_id,p_name,quantity,price,totalPrice)values(?,?,?,?,?,?)");
            
             ps.setInt(1,uid);
             ps.setInt(2,pid);
             ps.setString(3,productName);
             ps.setInt(4,Quantity);
             ps.setInt(5,Price);
             ps.setInt(6,totprice);
            
             ps.executeUpdate();
             
             JOptionPane.showMessageDialog(this,"Product added to cart!");
             this.setVisible(false);
           }
        catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
           }
         //}
        
    /*else
    {
        JOptionPane.showMessageDialog(this,"You are not signed in!!!!Please sign in first");
    }*/
      
        
    }//GEN-LAST:event_AddToCartActionPerformed
    
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        /*if(Category=="Mobiles and Accessories")
     {
         userpage u= new userpage(ID,Name,Signin);
        MobilesAndAccessories ma=new MobilesAndAccessories(ID,Name,Signin);
        u.setVisible(true);
        u.jDesktopPane2.add(ma);
        ma.setVisible(true);
        this.setVisible(false);
     }
        else if(Category=="Household and Kitchen Appliances")
     {
         userpage u= new userpage(ID,Name,Signin);
        HouseholdAndKitchen hk=new HouseholdAndKitchen(ID,Name,Signin);
        u.jDesktopPane2.add(hk);
        hk.setVisible(true);
        this.setVisible(false);
    } 
         else if(Category=="Furniture")
     {
         userpage u= new userpage(ID,Name,Signin);
        Furniture f=new Furniture(ID,Name,Signin);
        u.jDesktopPane2.add(f);
        f.setVisible(true);
        this.setVisible(false);
    }   
         else if(Category=="Books and Stationery")
     {
         userpage u= new userpage(ID,Name,Signin);
        BooksAndStationery b=new BooksAndStationery(ID,Name,Signin);
        u.jDesktopPane2.add(b);
        b.setVisible(true);
        this.setVisible(false);
    } 
     else if(Category=="Grocery")
     {
         userpage u= new userpage(ID,Name,Signin);
        Groceries g=new Groceries(ID,Name,Signin);
        u.jDesktopPane2.add(g);
        g.setVisible(true);
        this.setVisible(false);
     }
        else if(Category=="Daily Essentials")
     {
         userpage u= new userpage(ID,Name,Signin);
        DailyEssentials de=new DailyEssentials(ID,Name,Signin);
        u.jDesktopPane2.add(de);
        de.setVisible(true);
        this.setVisible(false);
    } */
 
    }//GEN-LAST:event_CancelActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int Quantity=Integer.parseInt(jSpinner1.getValue().toString());
        int Price=Integer.parseInt(cost.getText().toString());
        int tot=Price * Quantity;
        jLabel8.setText(String.valueOf(tot));
    }//GEN-LAST:event_jSpinner1StateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectedRow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectedRow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCart;
    private javax.swing.JButton Cancel;
    public javax.swing.JTextField cost;
    public javax.swing.JTextArea desc;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    public javax.swing.JLabel pic;
    public javax.swing.JTextField pname;
    private javax.swing.JLabel uid;
    // End of variables declaration//GEN-END:variables
}
