/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ecommerce;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Raheela Khanum
 */
public class userpage extends javax.swing.JFrame {

    /**
     * Creates new form userpage
     */
    public userpage() {
        initComponents();
         Connect();
    }
    
    String role;
    
    Connection con;
    PreparedStatement ps; 
    ResultSet rs;
    String Name;
    boolean Signin;
    int U_ID;
    String ID;
    
    public  userpage(String name,boolean Signin) 
    {
       initComponents();
        Connect();
        
       this.Name=name;
       this.Signin=Signin;
       More.setVisible(false);
       try
           {
            
            ps=con.prepareStatement("select * from user where name=?");
            ps.setString(1,Name);
            
            
            
            rs=ps.executeQuery();
            if(rs.next())
            { 
              ID=rs.getString("u_id");
              
            }
           }
        catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       if(Signin==false)
      {   
          More.setVisible(false);
          EditProfile.setVisible(false);
          Logout.setVisible(false);
          SignUp.setVisible(true);
          Login.setVisible(true);
          
      }
      else if(Signin==true)
        {
          SignUp.setVisible(false);
          Login.setVisible(false);
          
         }
       
       
      /*if(Name.equals("Ruksar") || Name.equals("Ruzaina"))
        {
            MyCart.setVisible(false);
            
            DeleteProduct.setVisible(true);
            UpdateProduct.setVisible(true);
            AddProduct.setVisible(true);         
        }
        
        else
        {
            More.setVisible(false);
            DeleteProduct.setVisible(false);
            UpdateProduct.setVisible(false);
            AddProduct.setVisible(false);         
        }*/
      
    }
    
    
    public  userpage(String id,String name,boolean Signin) 
    {
        initComponents();
        Connect();
        
        this.ID=id;
        this.Name=name;
       this.Signin=Signin;
       
       
       if(Signin==false)
      {   
          More.setVisible(false);
          EditProfile.setVisible(false);
          Logout.setVisible(false);
          SignUp.setVisible(true);
          Login.setVisible(true);
      }
      else if(Signin==true)
        {
          SignUp.setVisible(false);
          Login.setVisible(false);
         }
       
       
      if(Name.equals("Ruksar") || Name.equals("Ruzaina"))
        {
            MyCart.setVisible(false);
            DeleteProduct.setVisible(true);
            UpdateProduct.setVisible(true);
            AddProduct.setVisible(true);         
        }
        
        else
        {
            More.setVisible(false);
            DeleteProduct.setVisible(false);
            UpdateProduct.setVisible(false);
            AddProduct.setVisible(false);         
        }
       
    }
public void Connect()
      {
          try{
              Class.forName("com.mysql.cj.jdbc.Driver");
              con = DriverManager.getConnection("jdbc:mysql://localhost/ecommerce","root","Ruk@413255");
              }
          catch(ClassNotFoundException ex)
              {Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
               }
          catch (SQLException ex) {
            Logger.getLogger(userlog.class.getName()).log(Level.SEVERE, null, ex);
             }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HouseholdAndKitchen = new javax.swing.JButton();
        Furniture = new javax.swing.JButton();
        BooksAndStationery = new javax.swing.JButton();
        MobilesAccessories = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Grocery = new javax.swing.JButton();
        DailyEssentials = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Profile = new javax.swing.JMenu();
        EditProfile = new javax.swing.JMenuItem();
        SignUp = new javax.swing.JMenuItem();
        Login = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        MyCart = new javax.swing.JMenu();
        GoToCart = new javax.swing.JMenuItem();
        More = new javax.swing.JMenu();
        DeleteProduct = new javax.swing.JMenuItem();
        UpdateProduct = new javax.swing.JMenuItem();
        AddProduct = new javax.swing.JMenuItem();
        Orders = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane2.setPreferredSize(new java.awt.Dimension(1550, 800));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("SHOPPER'S STALL");
        jDesktopPane2.add(jLabel1);
        jLabel1.setBounds(590, 80, 470, 70);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Experience the most simple way of shopping!");
        jDesktopPane2.add(jLabel2);
        jLabel2.setBounds(670, 150, 550, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\user2 page.jpeg")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1138, 260));
        jDesktopPane2.add(jLabel3);
        jLabel3.setBounds(0, 0, 1550, 320);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Categories");
        jDesktopPane2.add(jLabel4);
        jLabel4.setBounds(0, 330, 210, 50);

        HouseholdAndKitchen.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\Household.jpeg")); // NOI18N
        HouseholdAndKitchen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HouseholdAndKitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HouseholdAndKitchenActionPerformed(evt);
            }
        });
        jDesktopPane2.add(HouseholdAndKitchen);
        HouseholdAndKitchen.setBounds(260, 400, 250, 250);

        Furniture.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\furniture.jpeg")); // NOI18N
        Furniture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Furniture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FurnitureActionPerformed(evt);
            }
        });
        jDesktopPane2.add(Furniture);
        Furniture.setBounds(520, 400, 250, 250);

        BooksAndStationery.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\Books&Stationery.jpeg")); // NOI18N
        BooksAndStationery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BooksAndStationery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BooksAndStationeryActionPerformed(evt);
            }
        });
        jDesktopPane2.add(BooksAndStationery);
        BooksAndStationery.setBounds(780, 400, 250, 250);

        MobilesAccessories.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\Mobiles&Accessories.png")); // NOI18N
        MobilesAccessories.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MobilesAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MobilesAccessoriesActionPerformed(evt);
            }
        });
        jDesktopPane2.add(MobilesAccessories);
        MobilesAccessories.setBounds(0, 400, 250, 250);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Mobiles and Accessories");
        jDesktopPane2.add(jLabel5);
        jLabel5.setBounds(10, 660, 220, 30);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("Household and");
        jDesktopPane2.add(jLabel10);
        jLabel10.setBounds(320, 660, 130, 26);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(205, 255, 255));
        jLabel6.setText("Kitchen Appliances");
        jDesktopPane2.add(jLabel6);
        jLabel6.setBounds(300, 690, 170, 30);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(205, 255, 255));
        jLabel7.setText("Furniture");
        jDesktopPane2.add(jLabel7);
        jLabel7.setBounds(600, 670, 90, 40);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(205, 255, 255));
        jLabel8.setText("Books and Stationery");
        jDesktopPane2.add(jLabel8);
        jLabel8.setBounds(820, 670, 190, 30);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(205, 255, 255));
        jLabel9.setText("Grocery");
        jDesktopPane2.add(jLabel9);
        jLabel9.setBounds(1140, 660, 80, 40);

        Grocery.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\Grocery.jpeg")); // NOI18N
        Grocery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Grocery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroceryActionPerformed(evt);
            }
        });
        jDesktopPane2.add(Grocery);
        Grocery.setBounds(1040, 400, 250, 250);

        DailyEssentials.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\DailyEssentials.jpeg")); // NOI18N
        DailyEssentials.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DailyEssentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyEssentialsActionPerformed(evt);
            }
        });
        jDesktopPane2.add(DailyEssentials);
        DailyEssentials.setBounds(1300, 400, 250, 250);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(205, 255, 255));
        jLabel11.setText("Daily Essentials");
        jDesktopPane2.add(jLabel11);
        jLabel11.setBounds(1360, 660, 140, 40);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(200, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(58, 40));

        jMenu2.setForeground(new java.awt.Color(0, 0, 255));
        jMenu2.setText("            Shopper's Stall");
        jMenu2.setFont(new java.awt.Font("Candara", 3, 24)); // NOI18N
        jMenu2.setMaximumSize(new java.awt.Dimension(900, 32767));
        jMenu2.setPreferredSize(new java.awt.Dimension(700, 20));
        jMenuBar1.add(jMenu2);

        Profile.setBorder(null);
        Profile.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\Profile.png")); // NOI18N
        Profile.setText("Profile");
        Profile.setActionCommand("Login");
        Profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Profile.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Profile.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Profile.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Profile.setIconTextGap(8);
        Profile.setMinimumSize(new java.awt.Dimension(20, 20));
        Profile.setPreferredSize(new java.awt.Dimension(150, 20));
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        EditProfile.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        EditProfile.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\EditProfile.png")); // NOI18N
        EditProfile.setText("Edit profile");
        EditProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileActionPerformed(evt);
            }
        });
        Profile.add(EditProfile);

        SignUp.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        SignUp.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\SignUp.png")); // NOI18N
        SignUp.setText("Sign up");
        SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        Profile.add(SignUp);

        Login.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Login.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\login-rounded.png")); // NOI18N
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setLabel("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Profile.add(Login);

        Logout.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\logout-rounded.png")); // NOI18N
        Logout.setText("Logout");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        Profile.add(Logout);

        jMenuBar1.add(Profile);

        MyCart.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\MyCart.png")); // NOI18N
        MyCart.setText("My cart");
        MyCart.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MyCart.setPreferredSize(new java.awt.Dimension(150, 20));
        MyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyCartActionPerformed(evt);
            }
        });
        MyCart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MyCartKeyPressed(evt);
            }
        });

        GoToCart.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GoToCart.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\MyCart.png")); // NOI18N
        GoToCart.setText("GoToCart");
        GoToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToCartActionPerformed(evt);
            }
        });
        MyCart.add(GoToCart);

        jMenuBar1.add(MyCart);

        More.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\more.png")); // NOI18N
        More.setText("More");
        More.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        More.setPreferredSize(new java.awt.Dimension(150, 20));
        More.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreActionPerformed(evt);
            }
        });

        DeleteProduct.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        DeleteProduct.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\Delete.png")); // NOI18N
        DeleteProduct.setText("Delete Product");
        DeleteProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProductActionPerformed(evt);
            }
        });
        More.add(DeleteProduct);

        UpdateProduct.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        UpdateProduct.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\Update.png")); // NOI18N
        UpdateProduct.setText("Update Product");
        UpdateProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProductActionPerformed(evt);
            }
        });
        More.add(UpdateProduct);

        AddProduct.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        AddProduct.setIcon(new javax.swing.ImageIcon("G:\\Ruksar 5thsem\\Project\\Icons&Images\\Add.png")); // NOI18N
        AddProduct.setText("Add Product");
        AddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductActionPerformed(evt);
            }
        });
        More.add(AddProduct);

        Orders.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Orders.setText("Orders");
        Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersActionPerformed(evt);
            }
        });
        More.add(Orders);

        jMenuBar1.add(More);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProductActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Select the Category!!");
    }//GEN-LAST:event_UpdateProductActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileActionPerformed

    private void EditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileActionPerformed
        // TODO add your handling code here:
        register r=new register(ID,Name,Signin);
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditProfileActionPerformed

    private void MobilesAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MobilesAccessoriesActionPerformed
        // TODO add your handling code here:
        
        MobilesAndAccessories ma=new MobilesAndAccessories(ID,Name,Signin);
         jDesktopPane2.add(ma);
         ma.setVisible(true);
        
    }//GEN-LAST:event_MobilesAccessoriesActionPerformed

    private void HouseholdAndKitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HouseholdAndKitchenActionPerformed
        // TODO add your handling code here:
        HouseholdAndKitchen h=new HouseholdAndKitchen(ID,Name,Signin);
         jDesktopPane2.add(h);
         h.setVisible(true);
    }//GEN-LAST:event_HouseholdAndKitchenActionPerformed

    private void FurnitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FurnitureActionPerformed
        // TODO add your handling code here:
        Furniture f=new Furniture(ID,Name,Signin);
        jDesktopPane2.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_FurnitureActionPerformed

    private void BooksAndStationeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BooksAndStationeryActionPerformed
        // TODO add your handling code here:
        BooksAndStationery b=new BooksAndStationery(ID,Name,Signin);
        jDesktopPane2.add(b);
        b.setVisible(true);
    }//GEN-LAST:event_BooksAndStationeryActionPerformed

    private void GroceryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroceryActionPerformed
        // TODO add your handling code here:
        
        Groceries g=new Groceries(ID,Name,Signin);
        jDesktopPane2.add(g);
        g.setVisible(true);
        
    }//GEN-LAST:event_GroceryActionPerformed

    private void DailyEssentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyEssentialsActionPerformed
        // TODO add your handling code here:
       DailyEssentials de=new DailyEssentials(ID,Name,Signin);
       jDesktopPane2.add(de);
       de.setVisible(true);
    }//GEN-LAST:event_DailyEssentialsActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
        register r=new register("");
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignUpActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        userlog u=new userlog();
        u.setVisible(true);
       
    }//GEN-LAST:event_LoginActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Signin=false;  
        this.setVisible(false);
        userpage u=new userpage("",Signin);
        u.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void MyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyCartActionPerformed
        // TODO add your handling code here:
        /*if(Signin==false)
        {
            JOptionPane.showMessageDialog(this,"You are not signed in!!!!Please sign in first");
            new userlog().setVisible(true);
            this.setVisible(false);
        }
        else
        {
            MyCart cart=new MyCart();
            cart.setVisible(true);
            this.setVisible(false);
        }*/
    }//GEN-LAST:event_MyCartActionPerformed

    private void MoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoreActionPerformed

    private void MyCartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MyCartKeyPressed
        // TODO add your handling code here:
        /*if(Signin==false)
        {
            JOptionPane.showMessageDialog(this,"You are not signed in!!!!Please sign in first");
            new userlog().setVisible(true);
            this.setVisible(false);
        }
        else
        {
            MyCart cart=new MyCart();
            cart.setVisible(true);
            this.setVisible(false);
        }*/
    }//GEN-LAST:event_MyCartKeyPressed

    private void GoToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToCartActionPerformed
        // TODO add your handling code here:
        if(Signin==false)
        {
            JOptionPane.showMessageDialog(this,"You are not signed in!!!!Please sign in first");
            new userlog().setVisible(true);
            this.setVisible(false);
        }
        else
        {
            try {
                U_ID=Integer.parseInt(ID);
            ps=con.prepareStatement("select * from cart where u_id=?");
            ps.setInt(1,U_ID);
            rs=ps.executeQuery();
            
            if(rs.next())
            {
                this.setVisible(false);
                MyCart cart=new MyCart(ID,Name,Signin);
                cart.setVisible(true);
                
            }
            
            else
            {
                JOptionPane.showMessageDialog(this,"Your cart is empty!!");
            }
        }
        
        catch (SQLException ex) {
            Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
        }
            //MyCart cart=new MyCart(Name,Signin);
            //cart.setVisible(true);
            //this.setVisible(false);
        }
    }//GEN-LAST:event_GoToCartActionPerformed

    private void AddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductActionPerformed
        // TODO add your handling code here:
        EnterCategory ec=new EnterCategory(Name,Signin);
        ec.setVisible(true);
    }//GEN-LAST:event_AddProductActionPerformed

    private void DeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProductActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,"Select the Category!!");
    }//GEN-LAST:event_DeleteProductActionPerformed

    private void OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersActionPerformed
        // TODO add your handling code here:
        Orders o=new Orders();
        o.setVisible(true);
    }//GEN-LAST:event_OrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                userpage u=new userpage("","",true);
                u.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddProduct;
    private javax.swing.JButton BooksAndStationery;
    private javax.swing.JButton DailyEssentials;
    private javax.swing.JMenuItem DeleteProduct;
    private javax.swing.JMenuItem EditProfile;
    private javax.swing.JButton Furniture;
    private javax.swing.JMenuItem GoToCart;
    private javax.swing.JButton Grocery;
    private javax.swing.JButton HouseholdAndKitchen;
    private javax.swing.JMenuItem Login;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JButton MobilesAccessories;
    private javax.swing.JMenu More;
    private javax.swing.JMenu MyCart;
    private javax.swing.JMenuItem Orders;
    private javax.swing.JMenu Profile;
    private javax.swing.JMenuItem SignUp;
    private javax.swing.JMenuItem UpdateProduct;
    public javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
